services:
  - type: web
    name: final-proyecto
    env: python
    buildCommand: pip install --upgrade pip && pip install -r app/requirements.txt
    startCommand: streamlit run app/app.py
    pythonVersion: 3.12.3